### ISSUE TITLE
Some icons in taskbar are missing

### ISSUE THREAD

**Issue by tekvsakdan** [davekeogh/xfce4-docklike-plugin#1]
Current version: 0.0\~git20210611.ee0fd75-0ppa1~21.04

Some icons in Xubuntu 21.04 in taskbar are missing. Only generic icon is displayed. The icons in the list are displayed correctly.

Panel Preferences:
![image](https://user-images.githubusercontent.com/620899/121926237-0d50d600-cd3e-11eb-9beb-1522762c1951.png)

Viber: 
![image](https://user-images.githubusercontent.com/620899/121926547-5d2f9d00-cd3e-11eb-8de0-ceb4ffcb1b38.png)

**Comment by davekeogh** [comment]
Can you do the following to help debug this issue?
- attach a copy of the desktop file and what directory it was in here
- run xprop in a terminal, click on the Viber window, copy everything printed and add it here.

**Comment by tekvsakdan** [comment]
A copy of the desktop file -> [viber.desktop.zip](https://github.com/davekeogh/xfce4-docklike-plugin/files/6652162/viber.desktop.zip)

Desktop file is located here -> `/usr/share/applications/`

xprop results

> WM_STATE(WM_STATE):
> 		window state: Normal
> 		icon window: 0x2580f900
> _NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
> _NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 24, 1
> _NET_WM_DESKTOP(CARDINAL) = 0
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_FOCUSED
> _NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x4600087
> _NET_WM_ICON(CARDINAL) = 
> XdndAware(ATOM) = BITMAP
> WM_NAME(STRING) = "Viber"
> _NET_WM_NAME(UTF8_STRING) = "Viber"
> _MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x0, 0x0
> _NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
> _XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
> WM_CLIENT_LEADER(WINDOW): window id # 0x4600033
> WM_HINTS(WM_HINTS):
> 		Client accepts input or input focus: True
> 		window id # of group leader: 0x4600033
> WM_CLIENT_MACHINE(STRING) = "sraka"
> _NET_WM_PID(CARDINAL) = 2357760
> _NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 73400454
> WM_CLASS(STRING) = "Viber", "ViberPC"
> WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
> WM_NORMAL_HINTS(WM_SIZE_HINTS):
> 		user specified location: 695, 807
> 		user specified size: 1278 by 1366
> 		program specified minimum size: 1089 by 580
> 		window gravity: Static

**Comment by davekeogh** [comment]
Oh okay. I see the problem. Thanks.

We are trying to use the `Icon=` value as the icon name rather than as a file path. I need to add some code to test for that.

**Comment by davekeogh** [comment]
This is fixed in main now.
