### ISSUE TITLE
Blue icons after mouse hover

### ISSUE THREAD

**Issue by tekvsakdan** [davekeogh/xfce4-docklike-plugin#11]
**Describe the bug**
Blue icons after mouse hover.

**To Reproduce**
1. ALT+F2
2. `xfce4-panel -r`
3. Hover icons with mouse
4. Blue icons

![image](https://user-images.githubusercontent.com/620899/122974025-27b82e80-d392-11eb-80a9-4d72aac6eada.png)
![image](https://user-images.githubusercontent.com/620899/122973893-03f4e880-d392-11eb-8032-23fde80acb22.png)

**Expected behavior**

No blue icons.

**Desktop (please complete the following information):**
 - OS: Xubuntu 21.04
 - Xfce: 4.16.2 
 - Plugin: 0.2.0git-UNKNOWN (0.0\~git20210621.09e7cd8-0ppa1~21.04)

**Comment by Mr-Crabman** [comment]
I can confirm this is happening. It was fixed last time (#2), but now it's happening again.

- OS: Xubuntu 20.04.2
- Xfce panel 4.14.3-1
- Plugin: 0.2.0git-UNKNOWN (0.0~git20210621.09e7cd8-0ppa1~20.04)

**Comment by davekeogh** [comment]
The latest commit should fix this issue. I have no idea why this happens with some themes and not others. I'll try to remember to test with Greybird before committing any CSS changes in the future.
