### ISSUE TITLE
The line in pop-up menu is not colored when we hover with mouse

### ISSUE THREAD

**Issue by tekvsakdan** [davekeogh/xfce4-docklike-plugin#12]
**Describe the bug**

The line in pop-up menu is not colored when we hover with mouse.

**To Reproduce**

1. Hover with mouse on icon with more than 1 window opened.
2. Hover with mouse over the pop-up menu.
3. When we hover over the line, the line is not colored as in Window Button plugin.

![image](https://user-images.githubusercontent.com/620899/123074815-eff3ca00-d417-11eb-84a8-85476a90d875.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/620899/123074389-8673bb80-d417-11eb-9d7d-ef435549883d.png)

**Desktop**

 - OS: Xubuntu 21.04
 - Xfce: 4.16
 - Plugin: 
 - Theme: default Greybird

**Comment by Mr-Crabman** [comment]
This happens to me too.

- OS: Xubuntu 20.04.2
- Xfce panel 4.14.3-1
- Plugin: 0.2.0git-UNKNOWN (`0.0~git20210622.a72d232-0ppa1~20.04`)
