### ISSUE TITLE
No hover color over icons anymore

### ISSUE THREAD

**Issue by tekvsakdan** [davekeogh/xfce4-docklike-plugin#13]
**Describe the bug**
No hover color over icons anymore.

**To Reproduce**
1. Install new version :)
2. Hover over icons

**Expected behavior**

Now
![image](https://user-images.githubusercontent.com/620899/123736909-52c6e480-d8a2-11eb-8635-980b139f490c.png)
![image](https://user-images.githubusercontent.com/620899/123737235-e26c9300-d8a2-11eb-91e2-857f5a87e2b5.png)

Expected
![image](https://user-images.githubusercontent.com/620899/123737061-991c4380-d8a2-11eb-8938-7eac7b0f3e4e.png)
![image](https://user-images.githubusercontent.com/620899/123737284-f7e1bd00-d8a2-11eb-98b5-2c48970be016.png)

**Desktop:**
 - OS: Xubuntu 21.04
 - Xfce: 4.16
 - Plugin: 0.0~git20210627.2f23127-0ppa1\~21.04
 - Themes: Greybird, Adwaita, Numix... none of them works

**Comment by Mr-Crabman** [comment]
Same problem for me here.

- OS: Xubuntu 20.04.2
- Xfce: 4.14.3-1
- Plugin: `0.0~git20210627.2f23127-0ppa1~20.04`

**Comment by davekeogh** [comment]
My bad. I miss-understood something in the docs. I reverted the bad commit.
