### ISSUE TITLE
Moving to gitlab.xfce.org

### ISSUE THREAD

**Issue by alexxcons** [davekeogh/xfce4-docklike-plugin#16]
Just to let you know: If you would like to move the project to [gitlab.xfce.org](gitlab.xfce.org), that's fine with me, and more important, the other xfce devs. Just register there and  get in contact with ochosi or Skunnyk to get things started.

On #xfce-dev you sometimes have to wait a day or two until the right people show up :)

If you want to idle on #xfce-dev, but you dont want to care for an IRC bouncer, try the [matrix bridge](https://matrix.to/#/#xfce-dev:libera.chat), so you dont miss messages.

**Comment by Skunnyk** [comment]
As seen on IRC, I created the project on gitlab.xfce.org side, on https://gitlab.xfce.org/panel-plugins/xfce4-docklike-plugin . You should be maintainer and have commit/merge request access. Later we can set up translation with transifex, and usage or our release manager / announcements :) Ping me on irc or open an issue on https://gitlab.xfce.org/infra/help for the next steps !

**Comment by andriybyelikov** [comment]
Will development continue on this GitHub repo or should we look to the GitLab repo from now on?

**Comment by davekeogh** [comment]
I'll probably archive this repo and add a link over to the new one after I've migrated the help pages and issues.
