### ISSUE TITLE
Missing Japanese Translation

### ISSUE THREAD

**Issue by Hayao0819** [davekeogh/xfce4-docklike-plugin#17]
I sent the pull request to upstream to translate to Japanese.
They are here.

[#27](https://github.com/nsz32/docklike-plugin/pull/27)
[#29](https://github.com/nsz32/docklike-plugin/pull/29)
[#48](https://github.com/nsz32/docklike-plugin/pull/48)

But in v0.3.0 , almost of them do not work.
I can't understand C/C++ so I cannot find the cause.

![image](https://user-images.githubusercontent.com/32128205/125937383-e94537c5-abd8-400c-8b64-566139e75bc7.png)

**Comment by Hayao0819** [comment]
In 0.2.0, it correctly work.
![image](https://user-images.githubusercontent.com/32128205/125938218-ec59d16d-dcc8-4961-afb8-b14c722bd6f4.png)

**Comment by davekeogh** [comment]
Thanks. Some of the English strings got changed a bit for better readability and I think I may need to manually to make some changes to the po files now.

I've been meaning to set up a secondary locale on my PC to test the translations, but haven't got around to it. I'll try do that this weekend and look into this.

**Comment by SwampRabbit** [comment]
@davekeogh can confirm, the .po files need some revisions.  I took care of a few quick, including Japanese since obviously there is a user who needs it. #21

**Comment by davekeogh** [comment]
I think the translations that we do have should all be getting pulled in now.

@Hayao0819 Can you make another PR with translations for the new strings?
