### ISSUE TITLE
Not a bug report but a question about this repo.

### ISSUE THREAD

**Issue by coreybruce** [davekeogh/xfce4-docklike-plugin#19]
Hi I know this isn't a bug report but is this just a fork or a continuation of the project that's newer and has bug fixes?

**Comment by davekeogh** [comment]
I feel like the project is mostly complete at this point. My plan is mostly just  to fix the remaining bugs and get this added to the official XFCE repos.

**Comment by coreybruce** [comment]
If that's the case than you should really take over as the current one is on hold and not fixing any issues or feature requests which I have reported also the AUR package should change to your repo .

https://github.com/nsz32/docklike-plugin/issues/107#issuecomment-882242987

https://github.com/nsz32/docklike-plugin/issues/107#issuecomment-882242987

**Comment by SwampRabbit** [comment]
He doesn't have to "take over", him forking it and maintaining it to this point is enough, nsz32 can always pull the commits up if he wants to.  Which is how it supposed to work.  

The transition to the Xfce GitLab repos is the right move long term for every Xfce user, this discussion was had on nsz32's Issues a long time ago.

And I agree, docklike is feature complete, with some minor niggles here and there.
Half the reason nsz32's version got to the point it was at is that everyone wanted something but no one contributed.

If someone is wanting more they should use dockbarx or something.

**Comment by coreybruce** [comment]
I know that he doesn't have to but it was a suggestion since he is doing bug fixes/patches but I am not sure if nsz32 is doing pulls on commits or completely keeping it on hold which is holding back users that are using the current AUR package for example or the repo itself if the bugs are being patched/fixed or even new additional features are being added on this repo.

I feel like it's complete other than the bugs that have come up or one additional feature I suggested which was to add a option to change the ability to freely moved pinned icons or use alt to do so as I find that is a  little annoying for users. Nonetheless I like the project and really want to help contribute with reports and idea.

**Comment by SwampRabbit** [comment]
AURs repo is the problem of the package maintainer, you did the right thing and contacted them.

The pins are able to be moved for a long time,[look here]( https://github.com/davekeogh/xfce4-docklike-plugin/wiki/Help)

All I'm saying is try to open Issues that have substance, you actually know are an issue, and maybe try and offer a solution or two while you're at it.  People need less work, not more.  ;)

Example: I believe there's an issue with translation strings in the .po files, I'll know more once I test the build.  Easy fixes, doesn't take coding anything, and

**Comment by coreybruce** [comment]
"AURs repo is the problem of the package maintainer, you did the right thing and contacted them."

I asked because if this was a replacement repo even temporarily I would report that to the AUR package maintainer to update to this repo hence why I am asking otherwise telling the maintainer to move to this repo when I have no idea if this is a replacement or not would be a bad idea and a waste of time.

"The pins are able to be moved for a long time,look here"

I know it is but you didn't read what I said, I never said they can't be moved but a option to freely move it without needing to press and hold alt should be a option. That is what I was saying.

"All I'm saying is try to open Issues that have substance, you actually know are an issue, and maybe try and offer a solution or two while you're at it. People need less work, not more. ;)"

I understand that but if a developer is reporting a issue on a unfamiliar project then they aren't always going to know what the exact cause of the issue is, how to debug it or how to fix it. Sometimes all they can do is just report it than work with the developer to further figure our the issue.

**Comment by SwampRabbit** [comment]
ya want to help me out doing this for the people who use this?  #21 

or we can just keep talking in circles  ;)
