### ISSUE TITLE
Launchers/windows are fully blue after being hovered over once.

### ISSUE THREAD

**Issue by Mr-Crabman** [davekeogh/xfce4-docklike-plugin#2]
**Describe the bug**
Every time I boot up things look fine, but after moving my mouse over a launcher or window, the entire icon gets a bright blue background, and so it's impossible to tell if I have any open windows for that program (or how many), without hovering over it to see the window list.

**To Reproduce**
Hover your mouse over any window or launcher.

**Desktop (please complete the following information):**
 - OS: Xubuntu 20.04.2
 - Xfce panel 4.14.3-1

According to the "About" menu, the version of the plugin is `0.2.0git-UNKNOWN`, according to Synaptic, the version is `0.0~git20210614.432776c-0ppa1~20.04`.

**Additional context**
This is what the bug looks like (in the following image, I have 3 Firefox windows open, but thanks to the bug I can't tell):

![image](https://user-images.githubusercontent.com/23131128/122067075-2cf20800-cdeb-11eb-8699-e4c14d633bb5.png)

The color of the "indicator" chosen in the properties menu doesn't affect this at all, and it doesn't become visible "on top" of the blue backdrop.

The issue started only a few hours ago, after the most recent docklike update.

**Comment by tekvsakdan** [comment]
I have a similar problem after the update.

Docklike: 0.0\~git20210614.432776c-0ppa1~21.04
OS: Xubuntu 21.04
Xfce panel: 4.16.2-1

![image](https://user-images.githubusercontent.com/620899/122081837-c0cdcf00-cdff-11eb-8e75-b38158197a16.png)

**Comment by davekeogh** [comment]
I'm making some changes internally to theme code. It's only half done though. This is the last commit that won't have this issue: https://github.com/davekeogh/xfce4-docklike-plugin/commit/da92783868d6dc00e27ef81a20f43a1c59b2c3d6 for the moment.

Could you add what GTK theme you are using? This issue only seems to happen with some of them.

**Comment by tekvsakdan** [comment]
I'm using default Greybird theme.

![image](https://user-images.githubusercontent.com/620899/122100956-11e7be00-ce14-11eb-9580-a0ed0e6d2cdd.png)

**Comment by Mr-Crabman** [comment]
I am also using Greybird, but testing with it, a similar problem occurs with all of the default themes/styles (as listed by tekvsakdan), the only difference is the color of the box differs.

**Comment by davekeogh** [comment]
I reverted the main branch back to before my theme changes and moved them to a new branch.
