### ISSUE TITLE
[Feature Request] New indicator style (number).

### ISSUE THREAD

**Issue by Mr-Crabman** [davekeogh/xfce4-docklike-plugin#3]
**Is your feature request related to a problem? Please describe.**
The indicators only show whether you have 0 (for a pinned launcher), 1, or 2+ windows open, so you can't tell the difference between 2, 3, 4, and so on many windows open.

**Describe the solution you'd like**
The default xfce "window buttons", when set to "always" do window grouping, have a number indicator, which can go quite high (haven't tested it any further than 8, but it probably goes way higher):

![image](https://user-images.githubusercontent.com/23131128/122074231-f28b6980-cdf0-11eb-8237-0699a607d7a6.png)

An option like that would be nice.

**Comment by davekeogh** [comment]
I'm rewriting some of the theme code to make it easier to add new indicator styles. This one that I will try to implement after that.

**Comment by davekeogh** [comment]
I've added a hidden option to show numeric indicator like this. Add `showWindowCount=true` to your config file. It's still a work in progress, positioning and readability on some themes is not good.
