### ISSUE TITLE
Move Pinned icons

### ISSUE THREAD

**Issue by RUSshy** [davekeogh/xfce4-docklike-plugin#38]
I would like to be able top move pinned items

Right now to achieve that i need to unpin everything and pin things in the desired order

It is not good because if you have many pinned items, it becomes unmanageable

Thanks

**Comment by SwampRabbit** [comment]
You can move pinned items by pressing and holding CTRL and Left-Clicking an item and dragging it.
https://github.com/davekeogh/xfce4-docklike-plugin/wiki/Help
