### ISSUE TITLE
Please don't hardcode a size request

### ISSUE THREAD

**Issue by HugLifeTiZ** [davekeogh/xfce4-docklike-plugin#39]
**Describe the bug**
The size request for the group buttons is currently hardcoded such that the width is 1.2x the panel size. This prevents themes and customizers from changing the margins via CSS.

**To Reproduce**
1. Open the GTK Inspector on the plugin.
2. Inspect one of the group buttons.
3. Find that margin, padding, and min-width are not set, and thus can't be changed.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Xfce 4.16
 - Plugin 0.3.0

**Additional context or images**
If I comment out [this line](https://github.com/davekeogh/xfce4-docklike-plugin/blob/3208582f74957b006cc4141e29d6ddd6610c51b2/src/Group.cpp#L278), it has the sizing of a regular Xfce panel icon button. If a default 1.2x size is desired, it may be better off as a min-width CSS property, so it can still be overridden.

**Comment by HugLifeTiZ** [comment]
By the way, thanks for taking up the torch on this from the original plugin writer. It's nice to have a better solution for a dock-style taskbar than what I had been doing. :)

**Comment by davekeogh** [comment]
Interesting, thanks for pointing this out.

I'm not sure why this is the case. There's a bunch of dead code like this that is leftover from when nsz32 was originally debugging and writing the plugin that can be safely removed though.

**Comment by HugLifeTiZ** [comment]
Thanks very much for the quick commit!
