### ISSUE TITLE
[Feature Request] When removing the plug-in from the panel, keep the settings

### ISSUE THREAD

**Issue by tekvsakdan** [davekeogh/xfce4-docklike-plugin#4]
When we remove the plug-in, the settings `~/.config/xfce4/panel/docklike-7.rc` are also removed. The next time you add a plug-in, you need to set everything up again. If you copy the settings and add a plug-in, those settings are deleted and you have to set everything.

This bug or a feature exist since the beginning. I think it would be great if the settings were not deleted.

**Comment by davekeogh** [comment]
This is just the way Xfce panel plugins work. The config file is tied to an instance of the plugin. It doesn't really make sense to me to implement this.

What I am adding, which will work in a similar way, is the ability to add a default config file in ~/.config/something
You can already sort of do this (if you have root) by adding a config file at XDG_CONFIG_DIRS/xfce4/panel/docklike.rc
