### ISSUE TITLE
Pinned applications remain on dock if they are uninstalled

### ISSUE THREAD

**Issue by SwampRabbit** [davekeogh/xfce4-docklike-plugin#41]
@davekeogh I hope you are well.  

One of our users reported if you uninstall a pinned application, lets say Firefox using apt, the pin remains upon panel restart, logout, and or reboot; however, the icon will change to the gear icon.

This in of itself is not a huge problem, makes sense because docklike doesn't know it was removed, but....

The pin then is somewhat in a "locked" state, Right-Clicking doesn't allow any action at all.  So a user can't unpin it that way.

Manually editing the ~/.config/xfce4/panel/docklike-2.rc is a current workaround.

This is on MX-21 Beta 2 (Debian 11 Bullseye) , using Xfce 4.16, and our current version of xfce4-docklike-plugin 0.3.0+git20210806.
I'll be packaging a new version, I just saw you starting making some movement, and wanted to wait.

Keep up the awesome work BTW!

Edit: added Debian release for clarity.

**Comment by davekeogh** [comment]
Hi. I hope you're well too.

This shouldn't be that tough to implement. There's already some code to detect when desktop files are changed. I just need to update the pins when that happens.

With regards to making a new release. I was thinking about some time soon. I've already moved the help page over to https://docs.xfce.org/panel-plugins/xfce4-docklike-plugin/start. I just need to read a bit more about the official release process and maybe poke some people in IRC. I may make a 0.3.1 release here on Github first though.

**Comment by SwampRabbit** [comment]
No rush at all on an official release, package maintainers just bump the version with the commit date (like above) or commit number if we need to.  ;)

The issue above isn't a show stopper either, just annoying if a user can't remove it via mouse clicks.  Not sure how many people install and pin apps just to uninstall them or how often.  Minor, but annoying issue.

Been watching the Xfce GitLab, let me know if you need anything, I can "try" to help.  :P

**Comment by SwampRabbit** [comment]
Can confirm that building with this commit fixes the issue perfectly.
