### ISSUE TITLE
icons too close to each other on latest release from xubuntu-dev ppa

### ISSUE THREAD

**Issue by denikris** [davekeogh/xfce4-docklike-plugin#42]
i install this plugin from [xubuntu-dev ppa](https://launchpad.net/~xubuntu-dev/+archive/ubuntu/extras?field.series_filter=focal), this release (2021-09-16) has weird appearance unlike the screenshot in this repo main page, the earlier version from ppa look normal. bellow is screenshot with forced icon size to 16 (theme [fluent-dark-compact](https://github.com/vinceliuice/Fluent-gtk-theme))
![image](https://user-images.githubusercontent.com/16707606/133871874-68fa9d1a-4aa5-4800-9e47-321cfef10fcb.png)

edit 1:
when using greybird or greybird dark, the icons is not that close(image below)
![image](https://user-images.githubusercontent.com/16707606/133890618-c7b4b49b-8ae6-4386-809a-384b09974a1e.png)

edit 2:
before apply css, the dock use class properties `.xfce4-panel.background button` from the theme (which is min-height and min-width is 16px in fluent-compact)
this is when i applied css `#docklike-plugin button {min-width:32px;}` while using fluent-dark-compact
![image](https://user-images.githubusercontent.com/16707606/133891661-be7aa4c2-2085-40ba-ad99-b8dfdbb8ee70.png)

**Comment by davekeogh** [comment]
Hi. Previously the buttons had a size request of 1.2x the panel width, which caused issues with some themes and prevented using some CSS. Now they just use the default sizing rules. If you like the wider buttons, then using the min-width property is the best solution.

**Comment by Mr-Crabman** [comment]
> Hi. Previously the buttons had a size request of 1.2x the panel width, which caused issues with some themes and prevented using some CSS. Now they just use the default sizing rules. If you like the wider buttons, then using the min-width property is the best solution.

Hi, this may be the wrong place to ask, but how do I set the min-width? I'm not sure where to apply CSS to this plugin.

**Comment by davekeogh** [comment]
@Mr-Crabman 
You can create a file at `~/.config/gtk-3.0/gtk.css` if it doesn't exist and copy any CSS into it.
You will need to restart the panel (`xfce4-panel -r`) afterwards.
