### ISSUE TITLE
Many thanks + an idea?

### ISSUE THREAD

**Issue by jcornuz** [davekeogh/xfce4-docklike-plugin#5]
Hello there,

First of all, many thanks for working on this plugin. This was a sorely missed functionnality of Xfce and it is super nice to see it implemented and working so well.

One thing find useful is to be able to define a minimum width for the plugin. This way opening / closing windows doesn't make the docklike plugin size change (and all the items on the panel jerk)... and I can keep my clock well centered ;)

So I made an extremely ugly (but working) implementation by adding 
gtk_widget_set_size_request (mBox, 650, -1); 
in the Dock.cpp init. Obvioulsy, it requires a recompile to change the size, so not very user friendly!

While I think this could be an interesting option and make Docklike plugin more polished I can also understand if you see this as a feature creep!

In any case, thanks for this super useful plugin.

**Comment by davekeogh** [comment]
Thanks. Can you refile this using the feature request template? (it got deleted for some reason)
Add a screenshot to illustrate if you can.
