### ISSUE TITLE
Add a min-width (height) to docklike-plugin

### ISSUE THREAD

**Issue by jcornuz** [davekeogh/xfce4-docklike-plugin#6]
Offer a new preference for minimum size (in pixels) so the user can define the minimum horizontal (for horizontal panel) or vertical (for vertical or deskbar panel) size of the docklike plugin.

Giving a defined size for the docklike plugin, we avoid a growing / shrinking dock whenever new windows are created or closed:
1) avoids having other plugins "jerk" around because of docklike plugin size modification.
2) allows precise (and fixed) positionning of other plugins no matter how many windows are open / closed.

Both of which are currently impossible with the current Xfce panel - use of extended separators doesn't solve any of these use case.

I did a crude test of the idea by adding the following in the init of Dock.cpp:
                gtk_widget_set_size_request (mBox, 650, -1); 

... and here is a (commented) screenshot of my current Xfce4 panel + docklike plugin to illustrate the point:

![docklike_width](https://user-images.githubusercontent.com/12205858/122490965-14cbe580-cfb1-11eb-9388-00f52a486f35.png)

Again, MANY THANKS for docklike plugin.

**Comment by davekeogh** [comment]
This seems simple enough. I can easily add this option. I might just add this as a hidden option though, as the settings dialog is getting pretty bloated.

The default window buttons plugin doesn't have an option like this either. Does it have the same issue?

**Comment by jcornuz** [comment]
A hidden option would be ideal - no clutter or obscure option on the settings dialog while giving the possibility to have the good stuff for those who know where to find it :) 

The default window buttons plugin has the same problem: size grows / shrinks depending on how many windows are open. Using a single expanded separator works, but using two (for example to have content centered on the panel) creates jerkiness and the content is never quite centered.
(if you look at "centering items on Xfce4 panel" you will see it is a issue that has been a pain in the neck for quite a while...)
